# Generated by Django 3.1.6 on 2021-02-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210221_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='album',
            field=models.ImageField(blank=True, null=True, upload_to='album/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
    ]
