# Generated by Django 3.1.6 on 2021-02-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210221_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
