# Generated by Django 3.1.6 on 2021-02-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210221_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
