# Generated by Django 3.1.6 on 2021-02-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210221_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
